# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := gKitStatic gKitShared image_viewer

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

gKitStatic: 
	@echo "==== Building gKitStatic ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f gKitStatic.make

gKitShared: 
	@echo "==== Building gKitShared ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f gKitShared.make

image_viewer: gKitStatic
	@echo "==== Building image_viewer ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f image_viewer.make

clean:
	@${MAKE} --no-print-directory -C . -f gKitStatic.make clean
	@${MAKE} --no-print-directory -C . -f gKitShared.make clean
	@${MAKE} --no-print-directory -C . -f image_viewer.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   gKitStatic"
	@echo "   gKitShared"
	@echo "   image_viewer"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
